version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: reporteai_db
    environment:
      POSTGRES_DB: reporteai_db
      POSTGRES_USER: reporteai
      POSTGRES_PASSWORD: reporteai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reporteai_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reporteai -d reporteai_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: reporteai_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - reporteai_network
    depends_on:
      - postgres


  reporte-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reporte-api
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reporteai_db
      SPRING_DATASOURCE_USERNAME: reporteai
      SPRING_DATASOURCE_PASSWORD: reporteai
    networks:
      - reporteai_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  reporteai_network:
    driver: bridge
